# fly.toml app configuration file generated for my-finance-api on 2024-07-23T11:08:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-finance-api'
primary_region = 'gig'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
